### PR TITLE
Add addional lighter installation instructions

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by mourisl** [comment]
Thanks for making Lighter easier to be used. I'm wondering whether it will update automatically. For example, if I release Lighter v1.1.2 and the user installs it through "conda", would they get the old version v1.1.1?

**Comment by bgruening** [comment]
@mourisl I (or you or someone else) needs to update the link to the new tarball and rebuild the package but after that you will get the new version. The old version will still exist and is installable by specifying the exact version, this enables reproducibility in Galaxy for example.

**Comment by bgruening** [comment]
Can this be merged?

**Comment by mourisl** [comment]
Sorry for the late reply. I was out of town and forgot to reply this.

Since this installation can not be updated automatically, the user may download a version they don't want to use. I prefer to demonstrating this installation method in another section or a new section, not in the official installation instructions. 

Thanks.

**Comment by bgruening** [comment]
Mh, the user always sees the version of the package during installation. It's like a debian package.
To which section should we move this? And what is about the Docker container and the Galaxy integration. All are versioned.

**Comment by bgruening** [comment]
Should we add a note, that this version might not be the latest version?

**Comment by mourisl** [comment]
I think we can create a new section like "Miscellaneous" or "Helpful tips". And I can introduce new features of Lighter in that section in future.

**Comment by bgruening** [comment]
Ok, changed it.

**Comment by mourisl** [comment]
Looks great! Thanks!

**Pull request merged**
